name: deploy website preview
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          extended: true
          hugo-version: '0.124.1'
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Build
        run: hugo --gc --minify
      - name: Deploy to Vercel
        id: vercel-deploy
        uses: amondnet/vercel-action@v25
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_STATIC }}
          working-directory: public
      - name: Preview URL
        run: |
          echo "Preview URL: ${{ steps.vercel-deploy.outputs.preview-url }}"